phase 1 submission
osrf/vrx-events pull request #104
Opened 2023-09-05 18:55 UTC by CrzongA

Submission for Charlie's Robotics Team from City University of Hong Kong

2023-09-06 20:57 UTC, caguero requested changes
Thanks for your VRX submission!

* [ ] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Your video is reachable.
* [ ] Verified that the WAMV is active in the stationkeeping task.

You commited two versions of `component_config.yaml` and `thruster_config.yaml`. Please commit only one version and into your team name directory.

I manually copied them for testing your submission and found that they have some indentation/spacing issue. I used this versions:
```
engine:
  - prefix: "left"
    position: "-2.373776 1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "right"
    position: "-2.373776 -1.027135 0.318237"
    orientation: "0.0 0.0 0.0"
  - prefix: "middle"
    position: "0 0 0.318237"
    orientation: "0.0 0.0 0.0"

```

```
wamv_camera:
    - name: front_left_camera
      visualize: False
      x: 0.75
      y: 0.1
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
    - name: front_right_camera
      visualize: False
      x: 0.75
      y: -0.1
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
    - name: far_left_camera
      visualize: False
      x: 0.75
      y: 0.3
      z: 1.5
      R: 0.0
      P: ${radians(15)}
      Y: 0.0
      post_Y: 0.0
wamv_gps:
    - name: gps_wamv
      x: -0.85
      y: 0.0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
wamv_imu:
    - name: imu_wamv
      x: 0.3
      y: -0.2
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
lidar:
    - name: lidar_wamv
      type: 16_beam
      x: 0.7
      y: 0.0
      z: 1.8
      R: 0.0
      P: ${radians(8)}
      Y: 0.0
      post_Y: 0.0
wamv_ball_shooter:
    - name: ball_shooter
      x: 0.55 
      y: -0.3 
      z: 1.3
      pitch: ${radians(-20)}
      yaw: 0.0
wamv_pinger:
    - sensor_name: receiver
      position: 1.0 0 -1.0


```

We don't see activity in your WAM-V in the `stationkeeping` task. Is this expected?

2023-09-07 01:12 UTC, CrzongA commented
Thank you for the review.
Should I squash the commits into one commit to comply to the requirement?
As for WAMV's movement, it is indeed supposed to move, a script is supposed to publish movement commands via the ROS topic. Is correction related to this allowed within today?

2023-09-07 16:25 UTC, caguero commented
> Thank you for the review. Should I squash the commits into one commit to comply to the requirement? As for WAMV's movement, it is indeed supposed to move, a script is supposed to publish movement commands via the ROS topic. Is correction related to this allowed within today?

No issues adding an extra commit, up to you.

2023-09-07 16:29 UTC, caguero approved these changes

2023-09-07 16:48 UTC, merged