Team EPOXSEA phase 2 solution
osrf/vrx-events pull request #116
Opened 2023-10-03 12:53 UTC by mad-hin

Our team have completed task 1, 2, 4, 5, 7. Other tasks are still working in it

2023-10-04 17:17 UTC, caguero approved these changes
Thanks for your VRX submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [x] Verified that the WAMV is active in the stationkeeping task.

All looking good!

2023-10-04 19:47 UTC, caguero requested changes
Minor request:

Could you leave your phase1 files untouched? This pull request should only contribute to phase2 in your case.

2023-10-05 01:44 UTC, mad-hin commented
Now it should only contains the phase 2 files, and the phase 1 files are untouched. If you have faced any issue, please let me know. Thank you

2023-10-05 19:09 UTC, caguero approved these changes

2023-10-05 19:09 UTC, merged