2023 final Arcturus
osrf/vrx-events pull request #153
Opened 2023-11-02 06:05 UTC by toyat522

This submission tackles tasks #1, #2, #4, #7

2023-11-02 22:03 UTC, caguero requested changes
Thanks for your submission!

* [x] Compliance tests for component and propulsion configurations passed.
* [x] Successfully able to access Docker image.
* [ ] Verified that the WAMV is active in the stationkeeping task

Your submission does not show activity on the stationkeeping task. This is the latest output from your console in case it helps:

```
[protobuf_client_node-11] [INFO] [1698962462.559105880] [rclcpp]: Looping until connected to gateway. Error 
[protobuf_client_node-11] system:111
   [009] Process: pRealm          has quit
   [008] Process: pNodeReporter   has quit
   [007] Process: uProcessWatch   has quit
   [006] Process: pMarinePIDV22   has quit
   [005] Process: pHelmIvP        has quit
   [004] Process: pLogger         has quit
   [003] Process: pParseWaypoint  has quit
   [002] Process: pParseGateway   has quit
   [001] Process: iMOOSGateway    has quit
   [000] Process: MOOSDB          has quit
```

I recommend you to carefully read the validation instructions to debug your issue and resubmit during the next 24 hours.

https://github.com/osrf/vrx/wiki/vrx_2023-validation


Good luck!

2023-11-03 18:47 UTC, toyat522 commented
I believe I have pushed the fixed to docker now

2023-11-03 19:25 UTC, caguero commented
> I believe I have pushed the fixed to docker now

And it's working now, good job!

The next step is to evaluate the docker image in the VRX simulation with the tasks/trials over the next few days.

Good luck!

2023-11-03 19:25 UTC, caguero approved these changes

2023-11-03 19:27 UTC, merged